### ISSUE TITLE
Cannot get a runnable plugin

### ISSUE THREAD

**Issue by SteppXXL** [philglover/pitclipse#64]
Hi there,

I failed in getting a plugin for my eclipse.

1. In marketplace there is an outdated (?) version (https://marketplace.eclipse.org/content/pitclipse ): 0.31.4.201401081810
1.1 it does not stop but stresses one core to 100%
[...]
17:02:53 PIT >> FINE : processed mutation in 52 ms.
17:02:53 PIT >> FINE : MutationIdentifier [location=Location [clazz=com.mercateo.catalog.deployment.server.command.builder.MediaServerFindCommandBuilder, method=createFindCommand, methodDesc=(Ljava/lang/String;Lcom/mercateo/catalog/deployment/api/serverhosts/MediaServerHost;Ljava/lang/String;ILcom/mercateo/catalog/deployment/api/common/SymlinkSupport;)Ljava/lang/String;], indexes=[98], mutator=org.pitest.mutationtest.engine.gregor.mutators.ReturnValsMutator] KILLED by com.mercateo.catalog.deployment.server.command.builder.MediaServerFindCommandBuilder1Test.test_with_symlinks(com.mercateo.catalog.deployment.server.command.builder.MediaServerFindCommandBuilder1Test)
17:02:53 PIT >> FINE : Exit code was - OK
17:02:53 PIT >> FINE : Slave exited ok

2. checked out your code
2.1. pitclipse-plugin/pom.xml refers to parent 1.1.4, pitclipse-parent/pom.xml has 1.1.5
2.2. in pitclipse-plugin/pom.xml there is reference to http://localhost:8081/nexus/content/groups/local-p2-mirror/ that does not work
2.3. after fixing 2.1 by setting to 1.1.5 and 2.2. by removing the local stuff I get the following exception
stephan@praetsch:/tmp/pitclipse/pitclipse-plugin> mvn clean install deploy -Pbundle
[INFO] Scanning for projects...
[WARNING] No explicit target runtime environment configuration. Build is platform dependent.
---------------------------------------------------
constituent[0]: file:/opt/extern/apache-maven-3.3.3/lib/aether-util-1.0.2.v20150114.jar
[...]
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.maven.execution.MavenSession.getRepositorySession()Lorg/sonatype/aether/RepositorySystemSession;
	at org.eclipse.tycho.core.maven.utils.PluginRealmHelper.execute(PluginRealmHelper.java:86)
	at org.eclipse.tycho.p2.resolver.P2TargetPlatformResolver.getDependencyMetadata(P2TargetPlatformResolver.java:159)
	at org.eclipse.tycho.p2.resolver.P2TargetPlatformResolver.setupProjects(P2TargetPlatformResolver.java:141)
	at org.eclipse.tycho.core.resolver.DefaultTychoDependencyResolver.setupProject(DefaultTychoDependencyResolver.java:76)
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:59)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:266)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

3. your linked release page is an 404 error: http://eclipse.pitest.org/release

Unfortunately there is no way to get a runnable plugin for me. I'd love to use PiTest in my Eclipse.
Can you help me?

Regards
Stephan

**Comment by philglover** [comment]
Hi,

Apologies, I'm currently in process of tidying up the build.  It's a complete mess in all honesty.

First things first, are you able to run pitest against your project using one of the other plugins e.g. ant or maven?

The version that installed via marketplace is the latest version, marketplace erroneously reports 0.31 for some reason.  You can confirm this by  checking in Help -> About -> Installation Details

I'll be updating the build process in the very near future, but building eclipse plugins with maven is not for the feint hearted!.

Regards

**Comment by SteppXXL** [comment]
Hi,

that means I won't consider building that plugin on my own because the latest version already is in the marketplace. Fine.

As mentioned on http://pitest.org/quickstart/maven/ PiTest runs well via maven (editing pom.xml and running mvn org.pitest:pitest-maven:mutationCoverage)

While I've been testing pitclipse with a simple code example it works - except of the error message "Browser cannot be initialized". PIT Summary is empty (probably caused by the browser-error?!) but PIT Mutations displays a result.

1. Do you know how to fix the browser-error? If I open an html-document in eclipse (via double click) it correctly opens my firefox and displays the document. Thus I suppose my eclipse is configured well.

2. I will simplify an example of my complex code that I want to test with pitclipse but pitclipse does not terminate.

Regards

**Comment by philglover** [comment]
Could you check Window -> Preferences -> General -> Web Browser 

If you are using an external browser, could you try setting it to the internal web browser and seeing what happens?

**Comment by SteppXXL** [comment]
I cannot use the internal web browser - the radio button is disabled. Strange.

**Comment by philglover** [comment]
Yes, that would certainly be a problem.  There are several guides for that issue - the actual issue depends on your OS and versions of eclipse etc but seems to hinge on libwebkitgtk.  Hopefully you can get it up and running.

In the medium term, the html view will go away.  The server side work is almost done for that, but I haven't looked at the UI controls yet.

**Comment by echebbi** [comment]
Pitclipse `2.0.0` has just been released and is now available in the Eclipse Marketplace.

I'll close this issue once an alternative for the current PIT Summary view is available — I took the liberty to update issue's title accordingly.

**Comment by helmutneukirchen** [comment]
As above "libwebkitgtk" is mentioned: on my Debian Buster, I had to install the package "libwebkit2gtk", and then everything worked..)
