### ISSUE TITLE
OptionParser exception

### ISSUE THREAD

**Issue by jiteshvassa** [philglover/pitclipse#67]
I've recently started to see an exception when attempting to run the plugin through Eclipse Version: Mars.2 Release (4.5.2), Build id: 20160218-0600

Here's the full stack:

Exception in thread "main" java.lang.NoSuchMethodError: joptsimple.OptionParser.acceptsAll(Ljava/util/List;Ljava/lang/String;)Ljoptsimple/OptionSpecBuilder;
    at org.pitest.mutationtest.commandline.OptionsParser.<init>(OptionsParser.java:122)
    at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:36)
    at org.pitest.pitclipse.pitrunner.PitRunner.runPIT(PitRunner.java:46)
    at org.pitest.pitclipse.pitrunner.PitRunner.main(PitRunner.java:25)

**Comment by philglover** [comment]
I'm on vacation and unable to look at this for a week.  Can I suggest you uninstall the plugin and install from the following update site http://eclipse.pitest.org/release-pre-juno/

**Comment by jiteshvassa** [comment]
Thanks, that resolves the issue.

**Comment by philglover** [comment]
Glad to hear it.  I don't suppose the project exhibiting this issue is open source is it?  Would help me write a test to prevent it happening again.

**Comment by jiteshvassa** [comment]
I'm afraid that the project isn't open source.

I'm wondering if the Eclipse installation may have been corrupted or perhaps the workspace, since I'm sure that I'd used it on that specific project before.

**Comment by philglover** [comment]
I think this and #66 are the same issue.  If for some reason old versions of the plugins are there, I think it may load all of them.  Classic behaviour for NoSuchMethod Error.  Investigating #66 now.
